import validationEmail from '../../../../src/utilities/validation/validationEmail';
import validationPassword from '../../../../src/utilities/validation/validationPass';
import validationComfrimPassword from '../../../../src/utilities/validation/validationComfrimPass';
import showHidePass from '../../../../src/utilities/showHidePass';

export const registerFormViewParams = {
    paramsTelOrEmail: {
        tag: 'span',
        classNames: ['Tel_text'],
        textContent: 'Telephone or Email',
        callback: null,
    },
    paramsMailInContainer:{
        tag: 'div',
        classNames: ['input_container'],
        textContent: '',
        callback: null,
    },
    paramsTelOrEmailInput:{
        tag: 'input',
        classNames: ['input', 'Email_input'],
        textContent: '',
        value: '',
        action: '',
        type: 'email',
        disabled: false,
        callback: validationEmail,
    },
    RequirementsToEmail: {
        tag: 'div',
        classNames: ['Requirements'],
        textContent: '',
        callback: null,
    },
    firstRequirementParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Email address must be properly formatted (e.g., user@example.com).',
        callback: null,
    },
    secondRequirementParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Email address must not contain leading or trailing whitespace.',
        callback: null,
    },
    thirdRequirementParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Email address must contain a domain name (e.g., example.com).',
        callback: null,
    },
    forthRequirementParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Email address must contain an \'@\' symbol separating local part and domain name.',
        callback: null,
    },
        paramsPassword: {
        tag: 'span',
        classNames: ['Password_text'],
        textContent: 'Password',
        callback: null,
    },
    paramsPasswordInContainer: {
        tag: 'div',
        classNames: ['input_container'],
        textContent: '',
        callback: null,
    },
    paramsPasswordInput: {
        tag: 'input',
        classNames: ['input', 'password_input'],
        textContent: '',
        value: '',
        action: '',
        type: 'password',
        disabled: false,
        callback: validationPassword,
    },
    RequirementsToPassword: {
        tag: 'div',
        classNames: ['Requirements'],
        textContent: '',
        callback: null,
    },
    firstRequirementPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must be at least 8 characters long.',
        callback: null,
    },
    secondRequirementPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must contain at least one uppercase letter (A-Z).',
        callback: null,
    },
    thirdRequirementPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must contain at least one lowercase letter (a-z).',
        callback: null,
    },
    forthRequirementPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must contain at least one digit (0-9).',
        callback: null,
    },
  
    FivesRequirementPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: '(Optional) Password must contain at least one special character (e.g., !@#$%^&*).',
        callback: null,
    },
    SixRequirementPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must not contain leading or trailing whitespace.',
        callback: null,
    },
    showHidePasswordParams: {
        tag: 'div',
        classNames: ['showPass'],
        textContent: '',
        callback: showHidePass,
    },
    paramsConfrimPassword: {
        tag: 'span',
        classNames: ['Password_text', 'Confrim_password_input'],
        textContent: 'Confrim Password',
        value: '',
        action: '',
        type: 'password',
        callback: null,
    },
    paramsConfrimPasswordInContainer: {
        tag: 'div',
        classNames: ['input_container'],
        textContent: '',
        callback: null,
    },
    paramsConfrinPasswordInput: {
        tag: 'input',
        classNames: ['input'],
        textContent: '',
        value: '',
        action: '',
        type: 'password',
        disabled: false,
        callback: validationComfrimPassword,
    },
    RequirementsToConfrimPassword: {
        tag: 'div',
        classNames: ['Requirements'],
        textContent: '',
        callback: null,
    },
    firstRequirementConfrimPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must be at least 8 characters long.',
        callback: null,
    },
    secondRequirementConfrimPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must contain at least one uppercase letter (A-Z).',
        callback: null,
    },
    thirdRequirementConfrimPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must contain at least one lowercase letter (a-z).',
        callback: null,
    },
  
    forthRequirementConfrimPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must contain at least one digit (0-9).',
        callback: null,
    },
    FivesRequirementConfrimPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: '(Optional) Password must contain at least one special character (e.g., !@#$%^&*).',
        callback: null,
    },
    SixRequirementConfrimPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Password must not contain leading or trailing whitespace.',
        callback: null,
    },
    SeventhRequirementConfrimPasswordParams: {
        tag: 'p',
        classNames: ['Requirement'],
        textContent: 'Passwords must match',
        callback: null,
    },
    showHideConfrimPasswordParams: {
        tag: 'div',
        classNames: ['showPass'],
        textContent: '',
        callback: showHidePass,
    },
    paramsRegisterButton: {
        tag: 'input',
        classNames: ['buttonRegSign'],
        textContent: 'Register',
        value: 'Register',
        action: '',
        type: 'submit',
        disabled: true,
        callback: null,
    },
    ParamslogInLink: {
        tag: 'span',
        classNames: ['logInLink'],
        textContent: 'Log In',
        callback: null,
    },
}